app = "givingbeans"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  LUCKY_ENV = "production"

[build]
  dockerfile = "./dockerfiles/webserver.Dockerfile"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = "lucky db.migrate"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 50
    soft_limit = 420
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[statics]]
    guest_path = "/app/public/css"
    url_prefix = "/css"

  [[statics]]
    guest_path = "/app/public/js"
    url_prefix = "/js"