databases:
  - name: The Giving Beans Primary
    databaseName: givingbeans
    user: givingbeans
    ipAllowList: []

services:
  - type: web
    name: The Giving Beans
    env: docker
    dockerfilePath: "./dockerfiles/webserver.Dockerfile"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: The Giving Beans Primary
          property: connectionString
      - key: LUCKY_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: APP_DOMAIN
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: SEND_GRID_KEY
        sync: false
